name: 3. Register Model
run-name: Register Latest BQML Model in Vertex AI

on:
  workflow_run:
    workflows: ["2. Model Training"]
    types: [completed]

jobs:
  register:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r model_requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Run Model Registration Script
      run: python -m src.register_bqml_models

    - name: Commit and push new files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a new branch name (e.g., "artifacts_1678886400")
        BRANCH_NAME="artifacts_bot_$(date +%s)"
          
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
        # Switch to the new branch
        git checkout -b $BRANCH_NAME
          
        git add -A
        # Commit the changes
        git commit -m "Add auto generated model artifacts and outputs" || echo "No changes to commit"
          
        # Push the new branch, not master
        git push -u origin $BRANCH_NAME

    - name: Notify Success
      if: success()
      run: echo "Model successfully registered in Vertex AI."

    - name: Notify Failure
      if: failure()
      run: echo "Model registration failed."

  notify:
    needs: register
    if: always()
    uses: ./.github/workflows/send_email.yml
    with:
      status: ${{ needs.register.result }}
      workflow_name: ${{ github.workflow }}
    secrets: inherit