name: 6. Bias Detection & Mitigation Pipeline
run-name: Run Bias Audit Pipeline

on:
  workflow_run:
    workflows: ["5. Evaluate Model"]
    types: [completed]

jobs:
  bias-pipeline:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      actions: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install dependencies
      run: pip install -r model_requirements.txt

    - name: Run Bias Detection & Mitigation Pipeline
      run: |
        echo "Starting Bias Audit Pipeline"
        python -m src.bias_pipeline

    - name: Commit and push new files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="artifacts_bot"
          
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
        # Switch to the new branch
        git checkout -b $BRANCH_NAME
          
        git add -A
        # Commit the changes
        git commit -m "Add auto generated model artifacts and outputs" || echo "No changes to commit"
          
        # Push the new branch, not master
        git push -u origin $BRANCH_NAME

    - name: Notify on success
      if: success()
      run: echo "Bias Pipeline executed successfully!"

    - name: Notify on failure
      if: failure()
      run: echo "Bias Pipeline failed!"

  notify:
    needs: bias-pipeline
    if: always()
    uses: ./.github/workflows/send_email.yml
    with:
      status: ${{ needs.bias-pipeline.result }}
      workflow_name: ${{ github.workflow }}
    secrets: inherit
