name: 8. Model Manager
run-name: Manage model versioning

on:
  workflow_run:
    workflows: ["7. Model Validation"]
    types: [completed]

jobs:
  model-manager:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r model_requirements.txt

    - name: Download model artifacts from previous run
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.event.workflow_run.id }}
      run: |
        echo "Downloading model artifacts"
        gh run download $RUN_ID -R $REPO -n trained-model

    - name: Move artifacts to correct locations
      run: |
        mkdir -p artifacts/
        mv trained_model_output/* artifacts/

    - name: Validate model
      run: |
        echo "Running validation."
        python -m src.model_manager

    - name: Commit and push new files
      if: success()
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git commit -m "Add auto generated model artifacts and outputs" || echo "No changes to commit"
        git push

    - name: Notify versioning success
      if: success()
      run: echo "Model versioning passed. Model approved!"

    - name: Notify versioning failure
      if: failure()
      run: echo "Model versioning failed â€” stopping pipeline."

  notify:
    needs: model-manager
    if: always()
    uses: ./.github/workflows/send_email.yml
    with:
      status: ${{ needs.model-manager.result }}
      workflow_name: ${{ github.workflow }}  
